### ISSUE TITLE
Upgrade pry-byebug

### ISSUE THREAD

**Issue by steakknife** [steakknife/spirit_hands#9]
Blocker is https://github.com/deivid-rodriguez/pry-byebug/issues/33
### Current gems
- spirit_hands (2.0.12)
- rails (5.0.0.1)
- pry-byebug (1.3.3)
- pry-remote (0.1.8)
### Desired gems
- pry-byebug ~> 3.4.0

**Comment by hms** [comment]
I would suggest that removing the dependency on pry-remote in favor of the significantly upgraded byebug is a good tradeoff.

**Comment by steakknife** [comment]
This is most likely. Thanks.

**Comment by steakknife** [comment]
Fixed in 2.1.1
